### ISSUE TITLE
first API sketch

### ISSUE THREAD

**Issue by TobiasRoeddiger** [OpenEarable/open_earable_flutter#1]
create all primary interfaces for open earable flutter library. required features:
- sensor configurations (defined by id)
- receive data (IMU; pressure, temp)
- set rgb led
- receive push button events
- control audio (play/pause/stop)

**Comment by TobiasRoeddiger** [comment]
take inspiration from: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/esense_flutter

**Comment by o-bagge** [comment]
At the moment, only the services **Sensor Service**, **Device Info Service** and **Parse Info Service** seem to be available?


- OpenEarable
  - bleManager
    - bool connected
    - DiscoveredDevice connectedDevice
    - Stream scanStream (Stream of scanned devices)
    - void startScan()
      - Scans available devices and initialises scanStream
    - void connectToDevice(DiscoveredDevice device)
      - connects to specified device
    - void write(Uuid serviceId, Uuid characteristicId, List<int> value)
    - Stream\<List\<int>> subscribe(Uuid serviceId, Uuid characteristicId)
    - Future\<List\<int>> read(Uuid serviceId, Uuid characteristicId)
  - deviceInfo
    - Future\<String> readDeviceIdentifier()
    - Future\<String> readDeviceGeneration()
  - sensorManager
    - void writeSensorConfig(OpenEarableSensorConfig sensorConfig)
      - OpenEarableSensorConfig(int sensorId, double samplingRate, int latency)
        - Uint8List byteList (sensor config as byte list)
    - Stream\<List\<int>> subscribeToSensorData(int sensorId)
      - returns stream of raw data of specific sensor
    - void disposeSensorDataController(int sensorId)
    - void disposeAllSensorDataControllers()
    - Stream getBatteryLevelStream()
    - void setLEDstate(int state)
    - Stream getButtonStateStream()
  - audioPlayer
    - void writeWAVState(int state, int size, String name)

**Comment by o-bagge** [comment]
At the moment, only the services **Sensor Service**, **Device Info Service** and **Parse Info Service** seem to be available?


- OpenEarable
  - bleManager
    - bool connected
    - DiscoveredDevice connectedDevice
    - Stream scanStream (Stream of scanned devices)
    - void startScan()
      - Scans available devices and initialises scanStream
    - void connectToDevice(DiscoveredDevice device)
      - connects to specified device
    - void write(Uuid serviceId, Uuid characteristicId, List<int> value)
    - Stream\<List\<int>> subscribe(Uuid serviceId, Uuid characteristicId)
    - Future\<List\<int>> read(Uuid serviceId, Uuid characteristicId)
  - sensorManager
    - void writeSensorConfig(OpenEarableSensorConfig sensorConfig)
      - OpenEarableSensorConfig(int sensorId, double samplingRate, int latency)
        - Uint8List byteList (sensor config as byte list)
    - Stream\<List\<int>> subscribeToSensorData(int sensorId)
      - returns stream of raw data of specific sensor
    - void disposeSensorDataController(int sensorId)
    - void disposeAllSensorDataControllers()
    - Stream getBatteryLevelStream()
    - Stream getButtonStateStream()
  - rgbLed
    - void setLEDstate(int state)
  - audioPlayer
    - void writeWAVState(int state, int size, String name)
  - Future\<String> readDeviceIdentifier()
  - Future\<String> readDeviceGeneration()

**Comment by o-bagge** [comment]
At the moment, only the services Sensor Service, Device Info Service and Parse Info Service seem to be available?

- OpenEarable
  - bleManager
    - bool connected
    - DiscoveredDevice connectedDevice
    - Stream scanStream (Stream of scanned devices)
    - void startScan()
      - Scans available devices and initialises scanStream
    - void connectToDevice(DiscoveredDevice device)
      - connects to specified device
    - void write(Uuid serviceId, Uuid characteristicId, List value)
    - Stream\<List\<int>> subscribe(Uuid serviceId, Uuid characteristicId)
    - Future\<List\<int>> read(Uuid serviceId, Uuid characteristicId)
  - sensorManager
    - void writeSensorConfig(OpenEarableSensorConfig sensorConfig)
      - OpenEarableSensorConfig(int sensorId, double samplingRate, int latency)
    - List\<int> byteList (sensor config as byte list)
    - Stream\<List\<int>> subscribeToSensorData(int sensorId)
      - returns stream of raw data of specific sensor
    - void disposeSensorDataController(int sensorId)
    - void disposeAllSensorDataControllers()
    - Stream getBatteryLevelStream()
    - Stream getButtonStateStream()
  - rgbLed
    - void setLEDstate(int state)
  - audioPlayer
    - void writeWAVState(int state, int size, String name)
    - Future\<String> readDeviceIdentifier()
    - Future\<String> readDeviceGeneration()
